### PR TITLE
Topic/plugin2

### PR DESCRIPTION
**Pull request by yanick**
Tweaking with the sugar I sprinkled on P2 since you started. :-)

### CODE REVIEW

**Comment by racke** [comment]
Sweet, thanks!

**Comment by racke** [comment]
OK, apparently it was too much sugar and now the stomach hurts:

```
t/01-basic.t ...... Use of uninitialized value $loginpage in regexp compilation at /home/racke/interchange/Dancer2-Plugin-Auth-Extensible/blib/lib/Dancer2/Plugin/Auth/Extensible.pm line 1221.
Use of uninitialized value $deniedpage in regexp compilation at /home/racke/interchange/Dancer2-Plugin-Auth-Extensible/blib/lib/Dancer2/Plugin/Auth/Extensible.pm line 1236.
Use of uninitialized value $loginpage in regexp compilation at /home/racke/interchange/Dancer2-Plugin-Auth-Extensible/blib/lib/Dancer2/Plugin/Auth/Extensible.pm line 1246.
Use of uninitialized value $logoutpage in regexp compilation at /home/racke/interchange/Dancer2-Plugin-Auth-Extensible/blib/lib/Dancer2/Plugin/Auth/Extensible.pm line 1251.
Use of uninitialized value $logoutpage in regexp compilation at /home/racke/interchange/Dancer2-Plugin-Auth-Extensible/blib/lib/Dancer2/Plugin/Auth/Extensible.pm line 1251.
"my" variable $user masks earlier declaration in same scope at t/lib/TestApp.pm line 31.
syntax error at t/lib/TestApp.pm line 13, near "require_login sub  "
syntax error at t/lib/TestApp.pm line 17, near "require_login sub "
syntax error at t/lib/TestApp.pm line 21, near "require_login sub "
syntax error at t/lib/TestApp.pm line 25, near "require_login sub "
syntax error at t/lib/TestApp.pm line 28, near "}"
syntax error at t/lib/TestApp.pm line 30, near "require_login sub "
syntax error at t/lib/TestApp.pm line 34, near "}"
syntax error at t/lib/TestApp.pm line 36, near "require_login sub "
syntax error at t/lib/TestApp.pm line 40, near "require_role BeerDrinker"
syntax error at t/lib/TestApp.pm line 44, near "require_role BearGrylls"
t/lib/TestApp.pm has too many errors.
Compilation failed in require at t/01-basic.t line 15.
BEGIN failed--compilation aborted at t/01-basic.t line 15.
t/01-basic.t ...... Dubious, test returned 255 (wstat 65280, 0xff00)
No subtests run 
```

Any clue, @yanick ?

**Comment by yanick** [comment]
On 2015-10-05 12:38 PM, Stefan Hornburg (Racke) wrote:
> Any clue, @yanick <https://github.com/yanick> ?

Turns out it works much better if I implement the keyword synonym thing,
instead of just having it in my head.

Dancer2::Plugin2 branch updated. Give it a whirl, it should be better, now.

`/.

**Comment by racke** [comment]
Yes, it works now after the vapourware materialized into real dancing code, all tests are passing.

Thanks!

**Comment by yanick** [comment]
On 2015-10-05 01:11 PM, Stefan Hornburg (Racke) wrote:
> Yes, it works now after the vapourware materialized into real dancing code

	\o/

**Pull request merged**
