### PR TITLE
Add logged_in_user_password_expired keyword

### PR DESCRIPTION
**Pull request by abeverley**
This adds functionality to help manage the expiry of passwords. It requires appropriate support from the relevant provider. See https://github.com/ctrlo/Dancer2-Plugin-Auth-Extensible-Provider-DBIC/commit/018eca35c461347b90cc9bd0b6957bcec1eb5709 for an example.

### CODE REVIEW

**Comment by racke** [comment]
What is the intended workflow? I suppose you want to force these users to change their password, right? In this case you need to prevent that they get access to protected routes.

**Comment by abeverley** [comment]
My intention was that it's up to the developer how to do the actual implemention: in my case, I'm doing a check in the ```before``` hook, and forwarding them to a password change page if required. The problem is likely to be that the password change page (or otherwise) is a protected route in itself.

I did think about doing this as an automatic forward to a configurable URL if the password has expired, but I thought that was overcomplicating it and leaving it less flexible for the developer.

How about I make this clear in the documentation and give an example?

**Comment by racke** [comment]
Yes, please clarify this in the documentation and provide an example.

**Comment by abeverley** [comment]
No problem, I've just pushed that now.

**Pull request merged**
